# Generated by Django 3.0.5 on 2020-06-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200422_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_lat',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='address_log',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
